//
//  PMUIFoundations.swift
//  Vaif R2 - VPN
//
//  Created by VAIF on 9/26/22.
//

import Foundation

public class PMUIFoundations {

    static let bundle = module ?? podsBundle ?? Bundle(for: PMUIFoundations.self)

    // Generated by SPM 5.3 on Xcode 12
    static var module: Bundle? = {
        //        let bundleName = "PMUIFoundations_PMUIFoundations"
        let bundleName = "Resources-UIFoundations"
        
        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,

            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: PMUIFoundations.self).resourceURL,

            // For command-line tools.
            Bundle.main.bundleURL
        ]

        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }

        return nil
    }()

    private static var podsBundle: Bundle? {
        guard let url = Bundle(for: PMUIFoundations.self).url(forResource: String(describing: PMUIFoundations.self), withExtension: "bundle"), let bundle = Bundle(url: url) else {
            return nil
        }
        return bundle
    }

}

