//
//  PMLogin+Bundle.swift
//  Vaif R2 - VPN
//
//  Created by VAIF on 9/21/22.
//

import Foundation

extension LoginAndSignup {
    static let bundle = module ?? podsBundle ?? Bundle(for: LoginAndSignup.self)

    // Generated by SPM 5.3 on Xcode 12
    static var module: Bundle? = {
        let bundleName = "Resources-LoginUI"

        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,

            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: LoginAndSignup.self).resourceURL,

            // For command-line tools.
            Bundle.main.bundleURL
        ]

        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }

        return nil
    }()

    private static var podsBundle: Bundle? {
        guard let url = Bundle(for: LoginAndSignup.self).url(forResource: String(describing: LoginAndSignup.self), withExtension: "bundle"),
              let bundle = Bundle(url: url) else {
            return nil
        }
        return bundle
    }
}


