# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
ENV["GYM_WORKSPACE"] = "/Users/vaif/VaifR2/Vaif R2 - VPN/Vaif R2 - VPN.xcworkspace"

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
	fastlane run increment_build_number

  end
end
